### ISSUE TITLE
Flutter Blue - Not able to read data from connected device

### ISSUE THREAD

**Issue by Mohammed3194** [MDSADABWASIM/Flutter_demo#1]
@MDSADABWASIM, Hi i am newbie into flutter, I have used `flutter_blue` plugin to connect the Bluetooth LE device. And trying to stream the data. My Bluetooth device it checks the air quality and i need to read it as a stream.

Have tried so many other samples and tutorials, i am not able understand how it works.

Please help out how can achieve this. Any help would be appreciated!!

**Comment by MDSADABWASIM** [comment]
In this [article](https://medium.com/flutter-community/flutter-for-bluetooth-devices-5594f105b146#a5c8)

I have already defined step by step how to connect to Bluetooth device and take data from it as a stream.
